theme: jekyll-theme-slate
title: signal SIGABRT
description: Finding and practicing what's missing in my coding, and what I can do for projects with things that I learned, CS/Swift/iOS fundamentals, mobile QA engineering, and more.
