theme: jekyll-theme-slate
title: Tatsuya "Brian" Moriguchi Github Pages
description: Looking for an iOS developer/Mobile App QA Engineer job opportunity to join a collaborative team environment
linkedin_url: https://linkedin.com/in/sigabrt
