theme: jekyll-theme-slate
title: Brian's Portfolio
description: Looking for an iOS developer/Mobile App QA Engineer job opportunity to join a collaborative team environment
linkedin_username: sigabrt
