theme: jekyll-theme-slate
title: Tatsuya's Portfolio
description: Looking for an iOS developer/Mobile App QA Engineer job opportunity to join a collaborative team environment
email: j0653arch@gmail.com
